version: '3.1'

services:

  shop-db:
    image: mysql:5.7
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    container_name: shop-db
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: 'shop_db'
      MYSQL_USER: 'babyan'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: 'root'

