version: '3.1'

services:
  shopapplication:
    depends_on:
      - shop-db
    build:
      context: .
    environment:
      SHOP_DB_USERNAME: ${SHOP_DB_USERNAME}
      SHOP_DB_PASSWORD: ${SHOP_DB_PASSWORD}
    restart: always
  shop-db:
    image: mysql:5.7
    restart: always
    container_name: shop-db
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: 'shop_db'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'babyan'
      MYSQL_PASSWORD: 'root'